### PR TITLE
statesync

### PR DESCRIPTION
**Pull request by faddat**
- fix ibc error
- update patch height
- update comment
- update CHANGELOG.md
- added state sync script

### CODE REVIEW

**Comment by zhangyelong** [comment]
@oncloudit Can you help to review this PR?

**Comment by oncloudit** [comment]
I have read your script, it's a very convenient way to start irishub node using state-sync.
However, there're some troubles during testing:
-  the snapshot need provided by rpc-nodes;
- it's unknown for newer to ready a trust height which be stored by rpc-nodes;
- don't know what's badgerdbp meaning;

So I modify the script according to docs "https://www.irisnet.org/docs/get-started/state-sync.html#procedure", and it success staring a new full node in china. Plz help review:
```
#!/bin/bash

iris init test
sed -i 's/minimum-gas-prices = ""/minimum-gas-prices = "0.025uiris"/' /root/.iris/config/app.toml
rm -f ~/.iris/config/genesis.json
wget -O ~/.iris/config/genesis.json https://raw.githubusercontent.com/irisnet/mainnet/master/config/genesis.json

# GET TRUST HASH AND TRUST HEIGHT
HEIGHT_HASH=$(wget -qO- http://34.82.96.8:26658/ | egrep -o '</br>[0-9]+: [0-9A-Z]+' | sed 's#</br>##' | tail -1)
HEIGHT=$(echo $HEIGHT_HASH | awk -F': ' '{print $1}')
HASH=$(echo $HEIGHT_HASH | awk -F': ' '{print $2}')

# TELL USER WHAT WE ARE DOING
echo "TRUST HEIGHT: $HEIGHT"
echo "TRUST HASH: $HASH"

# exort state sync vars
export IRIS_STATESYNC_ENABLE=true
# export IRIS_P2P_MAX_NUM_OUTBOUND_PEERS=200
export IRIS_STATESYNC_RPC_SERVERS="34.82.96.8:26657,34.77.68.145:26657"
export IRIS_STATESYNC_TRUST_HEIGHT=$HEIGHT
export IRIS_STATESYNC_TRUST_HASH=$HASH
export IRIS_STATESYNC_TRUST_PERIOD="168h0m0s"
export IRIS_P2P_PERSISTENT_PEERS="fcc1d9bc43163b20ce5163cf41a302b33f25375f@34.82.96.8:26656,3dcd46611a6a3d0aa22a4738a3e70dcc5c2a4d34@34.77.68.145:26656"

iris start
```

**Comment by faddat** [comment]
* Badgerdb is an alternative database supported by tm-db, and I tried it out to improve performance on the relayer becuase relaying really, really taxes the nodes.  but seems like rocksdb is better overall. 
* your changes are fine, and FYI, what you can actually do, is add env vars with a whole bunch of seeds or peers (global, let's say) and a whole bunch of RPC endpoints, and this makes it a much more decentralized sort of thing.  
* after this script has been enriched how I described above, we can in fact use it to ship validators on raspberry pi class computers.  You'd be surprised just how much the resource consumption drops after state sync.

**Review by zhangyelong — APPROVED** [review]

**Review by dreamer-zq — APPROVED** [review]

**Review by aofengli — APPROVED** [review]

**Comment by faddat** [comment]
I think it's best I resubmit this without any changes to .go files. 

Also, badgerdbp was a typo

2nd also, it turns out that badgerdb really doesn't improve performance, but rocksdb does very well!

-Jacob

**Pull request closed without merging**
