### PR TITLE
R4R: Add rewards query

### PR DESCRIPTION
**Pull request by chengwenxi**

### CODE REVIEW

**Comment by HaoyangLiu** [comment]
How about add querier interfaces in distribution module? You can refer to F1 distribution implementation.

**Comment by chengwenxi** [comment]
> How about add querier interfaces in distribution module? You can refer to F1 distribution implementation.

Will add querier interfaces and refactor all the distribution query API in next version, but the modification is too big for this version.

**Comment by wukongcheng** [comment]
It seems that this query interface will consume more calculation resources then others.

**Comment by chengwenxi** [comment]
> It seems that this query interface will consume more calculation resources then others.

Yes, so we'd better to refactor all the query API by adding querier interfaces in modules.

**Pull request merged**
