### PR TITLE
R4R: Make KMS available

### PR DESCRIPTION
**Pull request by chengwenxi**
- **account signing by Ledger** 

- **validator signing by Ledger and yubihsm**

### CODE REVIEW

**Comment by chengwenxi** [comment]
Supports: #1254

**Comment by chengwenxi** [comment]
Switch fields ordering to fit the latest Tendermint kms. 

https://github.com/irisnet/tendermint/pull/43

**Comment by adrianbrink** [comment]
> Switch fields ordering to fit the latest Tendermint kms.
> 
> [irisnet/tendermint#43](https://github.com/irisnet/tendermint/pull/43)

Thank you for this. It means that we don't have to maintain a separate branch of the KMS :-)

**Comment by chengwenxi** [comment]
> > Switch fields ordering to fit the latest Tendermint kms.
> > [irisnet/tendermint#43](https://github.com/irisnet/tendermint/pull/43)
> 
> Thank you for this. It means that we don't have to maintain a separate branch of the KMS :-)

But the consensus key bech32 prefix is a ​​const `cosmosvalconspub`, it's seems better to add the prefix in config file for different chain.

**Pull request merged**
