### PR TITLE
R4R: Make Ledger Nano S available

### PR DESCRIPTION
**Pull request by chengwenxi**
closes: https://github.com/irisnet/irishub/issues/1218

### CODE REVIEW

**Comment by chengwenxi** [comment]
Please compile code and upload cosmos app to ledger, Rf: https://github.com/cosmos/ledger-cosmos.

Make sure your ledger firmware version >= 1.5.5, [Update device firmware](https://support.ledger.com/hc/en-us/articles/360002997193)

**Comment by adrianbrink** [comment]
I get following error when trying to install on the latest macOS.

```
➜  irishub git:(320b51689) ✗ make install
"source scripts/setProdEnv.sh" to set compile environment variables for your product, or default values will be applied
InvariantLevel=error
NetworkType=mainnet
go install -tags "netgo cgo ledger" -ldflags " -X github.com/irisnet/irishub/version.GitCommit=320b51689 -X github.com/irisnet/irishub/types.InvariantLevel=error -X github.com/irisnet/irishub/types.NetworkType=mainnet" ./cmd/iris
# github.com/irisnet/irishub/vendor/github.com/zondax/hid
vendor/github.com/zondax/hid/hid_enabled.go:38:11: fatal error: 'hidapi/mac/hid.c' file not found
        #include "hidapi/mac/hid.c"
                 ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [install] Error 2
```

**Comment by chengwenxi** [comment]
> I get following error when trying to install on the latest macOS.
> 
> ```
> ➜  irishub git:(320b51689) ✗ make install
> "source scripts/setProdEnv.sh" to set compile environment variables for your product, or default values will be applied
> InvariantLevel=error
> NetworkType=mainnet
> go install -tags "netgo cgo ledger" -ldflags " -X github.com/irisnet/irishub/version.GitCommit=320b51689 -X github.com/irisnet/irishub/types.InvariantLevel=error -X github.com/irisnet/irishub/types.NetworkType=mainnet" ./cmd/iris
> # github.com/irisnet/irishub/vendor/github.com/zondax/hid
> vendor/github.com/zondax/hid/hid_enabled.go:38:11: fatal error: 'hidapi/mac/hid.c' file not found
>         #include "hidapi/mac/hid.c"
>                  ^~~~~~~~~~~~~~~~~~
> 1 error generated.
> make: *** [install] Error 2
> ```

Thank you for your report, it has been fixed.

**Comment by adrianbrink** [comment]
This works with a local testnet running with production parameters. The displayed values are really large since they are in attos, but besides that it's fine.

**Comment by chengwenxi** [comment]
will PR to release0.12, close now.

**Pull request closed without merging**
