### PR TITLE
R4R: Update Tendermint to v0.28.0

### PR DESCRIPTION
**Pull request by chengwenxi**
Update tendemrint version for test. @shilei-wang

### CODE REVIEW

**Comment by haifengxi** [comment]
We'll merge this PR when we update tendermint to v0.28 @chengwenxi

**Comment by chengwenxi** [comment]
> We'll merge this PR when we update tendermint to v0.28 @chengwenxi

It works on mainnet, let's release v0.28.

**Comment by haifengxi** [comment]
> > We'll merge this PR when we update tendermint to v0.28 @chengwenxi
> 
> While it works on mainnet, more testing should be done before release v0.28.

Yes, we'll create an RC for IRIS Hub based on irisnet/tendermint v0.28, and test everything out against the RC.

**Comment by chengwenxi** [comment]
> Yes, we'll create an RC for IRIS Hub based on irisnet/tendermint v0.28, and test everything out against the RC.

Done

**Pull request merged**
